### PR TITLE
add Pocket email per bug 1384394

### PR DESCRIPTION
**Pull request by peiying2**

### CODE REVIEW

**Comment by flodolo** [comment]
I'm honestly not sure that .lang files are the best way to translate emails, especially for one locale, but we don't have anything better. 

Did we get any feedback from localizer? Are they OK in localizing it?

Please add the pl file too.

**Comment by peiying2** [comment]
@flodolo Piotr did the review of an email post SF all hands, the translation work was done either by him or someone else.  He said it is ok to ask him moving forward.  

For this particular project, it is pl only. Jessica O said she has yet to share the new process with other locales about using Pontoon yet. She will meet with me to talk further next week.

**Comment by piotrdrag** [comment]
Pontoon displayed a notification about new strings in engagement, but they’re not available for Polish.

**Comment by flodolo** [comment]
Sorry, added now.

It should be up in Pontoon in about 5 minutes (next sync is at 18:50).

**Comment by piotrdrag** [comment]
Works now, thanks!

**Pull request merged**
