### PR TITLE
Reorganize tiles and snippets in subfolders for each year

### PR DESCRIPTION
**Pull request by flodolo**

### CODE REVIEW

**Comment by flodolo** [comment]
@mathjazz 
This is the pull request to move around files. It needs to be merged with 2 other PR for langchecker and webdashboard (see links above)

**Comment by flodolo** [comment]
Looks like I lost history, reverting and trying again.

**Comment by flodolo** [comment]
GitHub doesn't keep history of files even if you move them around with `git mv` individually :-1: 

Given how much these files are growing in number (at least +2 a month for some locale), I still think it's better to reorganize them now than later.

Can still check the log locally with `git log --follow`.

**Comment by mathjazz** [comment]
OK, I need to change relative paths in Pontoon; to sum up, what you did is basically rename:
`/path/to/YEAR_filename` -> `/path/to/YEAR/YEAR_filename`?

**Pull request merged**
